//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Plearn;

[assembly: RegisterDocumentType(CarouselFolder.CLASS_NAME, typeof(CarouselFolder))]

namespace CMS.DocumentEngine.Types.Plearn
{
	/// <summary>
	/// Represents a content item of type CarouselFolder.
	/// </summary>
	public partial class CarouselFolder : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Plearn.CarouselFolder";


		/// <summary>
		/// The instance of the class that provides extended API for working with CarouselFolder fields.
		/// </summary>
		private readonly CarouselFolderFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// CarouselFolderID.
		/// </summary>
		[DatabaseIDField]
		public int CarouselFolderID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("CarouselFolderID"), 0);
			}
			set
			{
				SetValue("CarouselFolderID", value);
			}
		}


		/// <summary>
		/// Element ID.
		/// </summary>
		[DatabaseField]
		public string ElementID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementID"), @"");
			}
			set
			{
				SetValue("ElementID", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CarouselFolder fields.
		/// </summary>
		[RegisterProperty]
		public CarouselFolderFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CarouselFolder fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CarouselFolderFields : AbstractHierarchicalObject<CarouselFolderFields>
		{
			/// <summary>
			/// The content item of type CarouselFolder that is a target of the extended API.
			/// </summary>
			private readonly CarouselFolder mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CarouselFolderFields" /> class with the specified content item of type CarouselFolder.
			/// </summary>
			/// <param name="instance">The content item of type CarouselFolder that is a target of the extended API.</param>
			public CarouselFolderFields(CarouselFolder instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// CarouselFolderID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.CarouselFolderID;
				}
				set
				{
					mInstance.CarouselFolderID = value;
				}
			}


			/// <summary>
			/// Element ID.
			/// </summary>
			public string ElementID
			{
				get
				{
					return mInstance.ElementID;
				}
				set
				{
					mInstance.ElementID = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CarouselFolder" /> class.
		/// </summary>
		public CarouselFolder() : base(CLASS_NAME)
		{
			mFields = new CarouselFolderFields(this);
		}

		#endregion
	}
}