//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.HXC;

[assembly: RegisterDocumentType(ClientScriptFolder.CLASS_NAME, typeof(ClientScriptFolder))]

namespace CMS.DocumentEngine.Types.HXC
{
	/// <summary>
	/// Represents a content item of type ClientScriptFolder.
	/// </summary>
	public partial class ClientScriptFolder : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "HXC.ClientScriptFolder";


		/// <summary>
		/// The instance of the class that provides extended API for working with ClientScriptFolder fields.
		/// </summary>
		private readonly ClientScriptFolderFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// NavigationFolderID.
		/// </summary>
		[DatabaseIDField]
		public int ClientScriptFolderID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ClientScriptFolderID"), 0);
			}
			set
			{
				SetValue("ClientScriptFolderID", value);
			}
		}


		/// <summary>
		/// Element ID.
		/// </summary>
		[DatabaseField]
		public string ElementID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementID"), @"");
			}
			set
			{
				SetValue("ElementID", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Folder name.
		/// </summary>
		[DatabaseField]
		public string FolderName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FolderName"), @"");
			}
			set
			{
				SetValue("FolderName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ClientScriptFolder fields.
		/// </summary>
		[RegisterProperty]
		public ClientScriptFolderFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ClientScriptFolder fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ClientScriptFolderFields : AbstractHierarchicalObject<ClientScriptFolderFields>
		{
			/// <summary>
			/// The content item of type ClientScriptFolder that is a target of the extended API.
			/// </summary>
			private readonly ClientScriptFolder mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ClientScriptFolderFields" /> class with the specified content item of type ClientScriptFolder.
			/// </summary>
			/// <param name="instance">The content item of type ClientScriptFolder that is a target of the extended API.</param>
			public ClientScriptFolderFields(ClientScriptFolder instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// NavigationFolderID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ClientScriptFolderID;
				}
				set
				{
					mInstance.ClientScriptFolderID = value;
				}
			}


			/// <summary>
			/// Element ID.
			/// </summary>
			public string ElementID
			{
				get
				{
					return mInstance.ElementID;
				}
				set
				{
					mInstance.ElementID = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}


			/// <summary>
			/// Folder name.
			/// </summary>
			public string FolderName
			{
				get
				{
					return mInstance.FolderName;
				}
				set
				{
					mInstance.FolderName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ClientScriptFolder" /> class.
		/// </summary>
		public ClientScriptFolder() : base(CLASS_NAME)
		{
			mFields = new ClientScriptFolderFields(this);
		}

		#endregion
	}
}