//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.HXC;

[assembly: RegisterDocumentType(ClientScript.CLASS_NAME, typeof(ClientScript))]

namespace CMS.DocumentEngine.Types.HXC
{
	/// <summary>
	/// Represents a content item of type ClientScript.
	/// </summary>
	public partial class ClientScript : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "HXC.ClientScript";


		/// <summary>
		/// The instance of the class that provides extended API for working with ClientScript fields.
		/// </summary>
		private readonly ClientScriptFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// HtmlCodeID.
		/// </summary>
		[DatabaseIDField]
		public int ClientScriptID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ClientScriptID"), 0);
			}
			set
			{
				SetValue("ClientScriptID", value);
			}
		}


		/// <summary>
		/// Script.
		/// </summary>
		[DatabaseField]
		public string ScriptContent
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ScriptContent"), @"");
			}
			set
			{
				SetValue("ScriptContent", value);
			}
		}


		/// <summary>
		/// ใส่ Node ID ตามด้วยเครื่องหมาย , เช่น
/insurance/Accident-insurance-page,/insurance/Health-insurance-page.
		/// </summary>
		[DatabaseField]
		public string NodeAliasPathList
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NodeAliasPathList"), @"");
			}
			set
			{
				SetValue("NodeAliasPathList", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ClientScript fields.
		/// </summary>
		[RegisterProperty]
		public ClientScriptFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ClientScript fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ClientScriptFields : AbstractHierarchicalObject<ClientScriptFields>
		{
			/// <summary>
			/// The content item of type ClientScript that is a target of the extended API.
			/// </summary>
			private readonly ClientScript mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ClientScriptFields" /> class with the specified content item of type ClientScript.
			/// </summary>
			/// <param name="instance">The content item of type ClientScript that is a target of the extended API.</param>
			public ClientScriptFields(ClientScript instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// HtmlCodeID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ClientScriptID;
				}
				set
				{
					mInstance.ClientScriptID = value;
				}
			}


			/// <summary>
			/// Script.
			/// </summary>
			public string ScriptContent
			{
				get
				{
					return mInstance.ScriptContent;
				}
				set
				{
					mInstance.ScriptContent = value;
				}
			}


			/// <summary>
			/// ใส่ Node ID ตามด้วยเครื่องหมาย , เช่น
/insurance/Accident-insurance-page,/insurance/Health-insurance-page.
			/// </summary>
			public string NodeAliasPathList
			{
				get
				{
					return mInstance.NodeAliasPathList;
				}
				set
				{
					mInstance.NodeAliasPathList = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ClientScript" /> class.
		/// </summary>
		public ClientScript() : base(CLASS_NAME)
		{
			mFields = new ClientScriptFields(this);
		}

		#endregion
	}
}