//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.HXC;

[assembly: RegisterDocumentType(CookieConsent.CLASS_NAME, typeof(CookieConsent))]

namespace CMS.DocumentEngine.Types.HXC
{
	/// <summary>
	/// Represents a content item of type CookieConsent.
	/// </summary>
	public partial class CookieConsent : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "HXC.CookieConsent";


		/// <summary>
		/// The instance of the class that provides extended API for working with CookieConsent fields.
		/// </summary>
		private readonly CookieConsentFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// CookieConsentID.
		/// </summary>
		[DatabaseIDField]
		public int CookieConsentID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("CookieConsentID"), 0);
			}
			set
			{
				SetValue("CookieConsentID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Effective Date.
		/// </summary>
		[DatabaseField]
		public DateTime EffectiveDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("EffectiveDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("EffectiveDate", value);
			}
		}


		/// <summary>
		/// Due Of Last X-Days.
		/// </summary>
		[DatabaseField]
		public int DueOfLastXDays
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("DueOfLastXDays"), 15);
			}
			set
			{
				SetValue("DueOfLastXDays", value);
			}
		}


		/// <summary>
		/// Cookie Store Key.
		/// </summary>
		[DatabaseField]
		public string CookieStoreKey
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CookieStoreKey"), @"");
			}
			set
			{
				SetValue("CookieStoreKey", value);
			}
		}


		/// <summary>
		/// Cookie Policy URL.
		/// </summary>
		[DatabaseField]
		public string CookiePolicyURL
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CookiePolicyURL"), @"");
			}
			set
			{
				SetValue("CookiePolicyURL", value);
			}
		}


		/// <summary>
		/// Resource String Prefix.
		/// </summary>
		[DatabaseField]
		public string ResourceStringPrefix
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ResourceStringPrefix"), @"");
			}
			set
			{
				SetValue("ResourceStringPrefix", value);
			}
		}


		/// <summary>
		/// Exclude Cookies.
		/// </summary>
		[DatabaseField]
		public string ExcludeCookies
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ExcludeCookies"), @"");
			}
			set
			{
				SetValue("ExcludeCookies", value);
			}
		}


		/// <summary>
		/// Enable Performance and functionality.
		/// </summary>
		[DatabaseField]
		public bool EnablePerformanceCookie
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EnablePerformanceCookie"), true);
			}
			set
			{
				SetValue("EnablePerformanceCookie", value);
			}
		}


		/// <summary>
		/// Set Performance and functionality (on/off).
		/// </summary>
		[DatabaseField]
		public bool SetPerformanceCookie
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("SetPerformanceCookie"), true);
			}
			set
			{
				SetValue("SetPerformanceCookie", value);
			}
		}


		/// <summary>
		/// Enable Analytics and customization.
		/// </summary>
		[DatabaseField]
		public bool EnableAnalyticCookie
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EnableAnalyticCookie"), true);
			}
			set
			{
				SetValue("EnableAnalyticCookie", value);
			}
		}


		/// <summary>
		/// Set Analytics and customization (on/off).
		/// </summary>
		[DatabaseField]
		public bool SetAnalyticCookie
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("SetAnalyticCookie"), true);
			}
			set
			{
				SetValue("SetAnalyticCookie", value);
			}
		}


		/// <summary>
		/// Separate By "|".
		/// </summary>
		[DatabaseField]
		public string AnalyticCookieDomain
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AnalyticCookieDomain"), @"");
			}
			set
			{
				SetValue("AnalyticCookieDomain", value);
			}
		}


		/// <summary>
		/// Separate by "|".
		/// </summary>
		[DatabaseField]
		public string AnalyticCookiePrefix
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AnalyticCookiePrefix"), @"");
			}
			set
			{
				SetValue("AnalyticCookiePrefix", value);
			}
		}


		/// <summary>
		/// Separate by "|".
		/// </summary>
		[DatabaseField]
		public string AnalyticDeleteCookie
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AnalyticDeleteCookie"), @"");
			}
			set
			{
				SetValue("AnalyticDeleteCookie", value);
			}
		}


		/// <summary>
		/// Enable Advertising.
		/// </summary>
		[DatabaseField]
		public bool EnableAdvertisingCookie
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EnableAdvertisingCookie"), true);
			}
			set
			{
				SetValue("EnableAdvertisingCookie", value);
			}
		}


		/// <summary>
		/// Set Advertising (on/off).
		/// </summary>
		[DatabaseField]
		public bool SetAdvertisingCookie
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("SetAdvertisingCookie"), false);
			}
			set
			{
				SetValue("SetAdvertisingCookie", value);
			}
		}


		/// <summary>
		/// Separate by "|".
		/// </summary>
		[DatabaseField]
		public string AdvertisingCookieDomain
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AdvertisingCookieDomain"), @"");
			}
			set
			{
				SetValue("AdvertisingCookieDomain", value);
			}
		}


		/// <summary>
		/// Separate by "|".
		/// </summary>
		[DatabaseField]
		public string AdvertisingCookiePrefix
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AdvertisingCookiePrefix"), @"");
			}
			set
			{
				SetValue("AdvertisingCookiePrefix", value);
			}
		}


		/// <summary>
		/// Separate by "|".
		/// </summary>
		[DatabaseField]
		public string AdvertisingDeleteCookie
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AdvertisingDeleteCookie"), @"");
			}
			set
			{
				SetValue("AdvertisingDeleteCookie", value);
			}
		}


		/// <summary>
		/// Enable Social networking.
		/// </summary>
		[DatabaseField]
		public bool EnableSocialCookie
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EnableSocialCookie"), true);
			}
			set
			{
				SetValue("EnableSocialCookie", value);
			}
		}


		/// <summary>
		/// Set Social networking (on/off).
		/// </summary>
		[DatabaseField]
		public bool SetSocialCookie
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("SetSocialCookie"), true);
			}
			set
			{
				SetValue("SetSocialCookie", value);
			}
		}


		/// <summary>
		/// Separate by "|".
		/// </summary>
		[DatabaseField]
		public string SocialCookieDomain
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SocialCookieDomain"), @"");
			}
			set
			{
				SetValue("SocialCookieDomain", value);
			}
		}


		/// <summary>
		/// Separate by "|".
		/// </summary>
		[DatabaseField]
		public string SocialCookiePrefix
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SocialCookiePrefix"), @"");
			}
			set
			{
				SetValue("SocialCookiePrefix", value);
			}
		}


		/// <summary>
		/// Separate by "|".
		/// </summary>
		[DatabaseField]
		public string SocialDeleteCookie
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SocialDeleteCookie"), @"");
			}
			set
			{
				SetValue("SocialDeleteCookie", value);
			}
		}


		/// <summary>
		/// Enable Policy Additional Note .
		/// </summary>
		[DatabaseField]
		public bool EnablePolicyAdditionalNote
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EnablePolicyAdditionalNote"), true);
			}
			set
			{
				SetValue("EnablePolicyAdditionalNote", value);
			}
		}


		/// <summary>
		/// Resource String Policy Additional Note.
		/// </summary>
		[DatabaseField]
		public string PolicyAdditionalNoteResourceString
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PolicyAdditionalNoteResourceString"), @"");
			}
			set
			{
				SetValue("PolicyAdditionalNoteResourceString", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CookieConsent fields.
		/// </summary>
		[RegisterProperty]
		public CookieConsentFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CookieConsent fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CookieConsentFields : AbstractHierarchicalObject<CookieConsentFields>
		{
			/// <summary>
			/// The content item of type CookieConsent that is a target of the extended API.
			/// </summary>
			private readonly CookieConsent mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CookieConsentFields" /> class with the specified content item of type CookieConsent.
			/// </summary>
			/// <param name="instance">The content item of type CookieConsent that is a target of the extended API.</param>
			public CookieConsentFields(CookieConsent instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// CookieConsentID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.CookieConsentID;
				}
				set
				{
					mInstance.CookieConsentID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Effective Date.
			/// </summary>
			public DateTime EffectiveDate
			{
				get
				{
					return mInstance.EffectiveDate;
				}
				set
				{
					mInstance.EffectiveDate = value;
				}
			}


			/// <summary>
			/// Due Of Last X-Days.
			/// </summary>
			public int DueOfLastXDays
			{
				get
				{
					return mInstance.DueOfLastXDays;
				}
				set
				{
					mInstance.DueOfLastXDays = value;
				}
			}


			/// <summary>
			/// Cookie Store Key.
			/// </summary>
			public string CookieStoreKey
			{
				get
				{
					return mInstance.CookieStoreKey;
				}
				set
				{
					mInstance.CookieStoreKey = value;
				}
			}


			/// <summary>
			/// Cookie Policy URL.
			/// </summary>
			public string CookiePolicyURL
			{
				get
				{
					return mInstance.CookiePolicyURL;
				}
				set
				{
					mInstance.CookiePolicyURL = value;
				}
			}


			/// <summary>
			/// Resource String Prefix.
			/// </summary>
			public string ResourceStringPrefix
			{
				get
				{
					return mInstance.ResourceStringPrefix;
				}
				set
				{
					mInstance.ResourceStringPrefix = value;
				}
			}


			/// <summary>
			/// Exclude Cookies.
			/// </summary>
			public string ExcludeCookies
			{
				get
				{
					return mInstance.ExcludeCookies;
				}
				set
				{
					mInstance.ExcludeCookies = value;
				}
			}


			/// <summary>
			/// Enable Performance and functionality.
			/// </summary>
			public bool EnablePerformanceCookie
			{
				get
				{
					return mInstance.EnablePerformanceCookie;
				}
				set
				{
					mInstance.EnablePerformanceCookie = value;
				}
			}


			/// <summary>
			/// Set Performance and functionality (on/off).
			/// </summary>
			public bool SetPerformanceCookie
			{
				get
				{
					return mInstance.SetPerformanceCookie;
				}
				set
				{
					mInstance.SetPerformanceCookie = value;
				}
			}


			/// <summary>
			/// Enable Analytics and customization.
			/// </summary>
			public bool EnableAnalyticCookie
			{
				get
				{
					return mInstance.EnableAnalyticCookie;
				}
				set
				{
					mInstance.EnableAnalyticCookie = value;
				}
			}


			/// <summary>
			/// Set Analytics and customization (on/off).
			/// </summary>
			public bool SetAnalyticCookie
			{
				get
				{
					return mInstance.SetAnalyticCookie;
				}
				set
				{
					mInstance.SetAnalyticCookie = value;
				}
			}


			/// <summary>
			/// Separate By "|".
			/// </summary>
			public string AnalyticCookieDomain
			{
				get
				{
					return mInstance.AnalyticCookieDomain;
				}
				set
				{
					mInstance.AnalyticCookieDomain = value;
				}
			}


			/// <summary>
			/// Separate by "|".
			/// </summary>
			public string AnalyticCookiePrefix
			{
				get
				{
					return mInstance.AnalyticCookiePrefix;
				}
				set
				{
					mInstance.AnalyticCookiePrefix = value;
				}
			}


			/// <summary>
			/// Separate by "|".
			/// </summary>
			public string AnalyticDeleteCookie
			{
				get
				{
					return mInstance.AnalyticDeleteCookie;
				}
				set
				{
					mInstance.AnalyticDeleteCookie = value;
				}
			}


			/// <summary>
			/// Enable Advertising.
			/// </summary>
			public bool EnableAdvertisingCookie
			{
				get
				{
					return mInstance.EnableAdvertisingCookie;
				}
				set
				{
					mInstance.EnableAdvertisingCookie = value;
				}
			}


			/// <summary>
			/// Set Advertising (on/off).
			/// </summary>
			public bool SetAdvertisingCookie
			{
				get
				{
					return mInstance.SetAdvertisingCookie;
				}
				set
				{
					mInstance.SetAdvertisingCookie = value;
				}
			}


			/// <summary>
			/// Separate by "|".
			/// </summary>
			public string AdvertisingCookieDomain
			{
				get
				{
					return mInstance.AdvertisingCookieDomain;
				}
				set
				{
					mInstance.AdvertisingCookieDomain = value;
				}
			}


			/// <summary>
			/// Separate by "|".
			/// </summary>
			public string AdvertisingCookiePrefix
			{
				get
				{
					return mInstance.AdvertisingCookiePrefix;
				}
				set
				{
					mInstance.AdvertisingCookiePrefix = value;
				}
			}


			/// <summary>
			/// Separate by "|".
			/// </summary>
			public string AdvertisingDeleteCookie
			{
				get
				{
					return mInstance.AdvertisingDeleteCookie;
				}
				set
				{
					mInstance.AdvertisingDeleteCookie = value;
				}
			}


			/// <summary>
			/// Enable Social networking.
			/// </summary>
			public bool EnableSocialCookie
			{
				get
				{
					return mInstance.EnableSocialCookie;
				}
				set
				{
					mInstance.EnableSocialCookie = value;
				}
			}


			/// <summary>
			/// Set Social networking (on/off).
			/// </summary>
			public bool SetSocialCookie
			{
				get
				{
					return mInstance.SetSocialCookie;
				}
				set
				{
					mInstance.SetSocialCookie = value;
				}
			}


			/// <summary>
			/// Separate by "|".
			/// </summary>
			public string SocialCookieDomain
			{
				get
				{
					return mInstance.SocialCookieDomain;
				}
				set
				{
					mInstance.SocialCookieDomain = value;
				}
			}


			/// <summary>
			/// Separate by "|".
			/// </summary>
			public string SocialCookiePrefix
			{
				get
				{
					return mInstance.SocialCookiePrefix;
				}
				set
				{
					mInstance.SocialCookiePrefix = value;
				}
			}


			/// <summary>
			/// Separate by "|".
			/// </summary>
			public string SocialDeleteCookie
			{
				get
				{
					return mInstance.SocialDeleteCookie;
				}
				set
				{
					mInstance.SocialDeleteCookie = value;
				}
			}


			/// <summary>
			/// Enable Policy Additional Note .
			/// </summary>
			public bool EnablePolicyAdditionalNote
			{
				get
				{
					return mInstance.EnablePolicyAdditionalNote;
				}
				set
				{
					mInstance.EnablePolicyAdditionalNote = value;
				}
			}


			/// <summary>
			/// Resource String Policy Additional Note.
			/// </summary>
			public string PolicyAdditionalNoteResourceString
			{
				get
				{
					return mInstance.PolicyAdditionalNoteResourceString;
				}
				set
				{
					mInstance.PolicyAdditionalNoteResourceString = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CookieConsent" /> class.
		/// </summary>
		public CookieConsent() : base(CLASS_NAME)
		{
			mFields = new CookieConsentFields(this);
		}

		#endregion
	}
}