//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.HXC;

[assembly: RegisterDocumentType(LayoutHeadSettings.CLASS_NAME, typeof(LayoutHeadSettings))]

namespace CMS.DocumentEngine.Types.HXC
{
	/// <summary>
	/// Represents a content item of type LayoutHeadSettings.
	/// </summary>
	public partial class LayoutHeadSettings : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "HXC.LayoutHeadSettings";


		/// <summary>
		/// The instance of the class that provides extended API for working with LayoutHeadSettings fields.
		/// </summary>
		private readonly LayoutHeadSettingsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// LayoutSettingsID.
		/// </summary>
		[DatabaseIDField]
		public int LayoutHeadSettingsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("LayoutHeadSettingsID"), 0);
			}
			set
			{
				SetValue("LayoutHeadSettingsID", value);
			}
		}


		/// <summary>
		/// Meta data zone.
		/// </summary>
		[DatabaseField]
		public string MetaDataZone
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MetaDataZone"), @"");
			}
			set
			{
				SetValue("MetaDataZone", value);
			}
		}


		/// <summary>
		/// Favicon type.
		/// </summary>
		[DatabaseField]
		public int FaviconType
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("FaviconType"), 1);
			}
			set
			{
				SetValue("FaviconType", value);
			}
		}


		/// <summary>
		/// Favicon link.
		/// </summary>
		[DatabaseField]
		public string FaviconLink
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FaviconLink"), @"");
			}
			set
			{
				SetValue("FaviconLink", value);
			}
		}


		/// <summary>
		/// Favicon image.
		/// </summary>
		[DatabaseField]
		public string FaviconImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FaviconImage"), @"");
			}
			set
			{
				SetValue("FaviconImage", value);
			}
		}


		/// <summary>
		/// Favicon image type.
		/// </summary>
		[DatabaseField]
		public string FaviconImageType
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FaviconImageType"), @"");
			}
			set
			{
				SetValue("FaviconImageType", value);
			}
		}


		/// <summary>
		/// CSS/Link zone.
		/// </summary>
		[DatabaseField]
		public string LinkZone
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkZone"), @"");
			}
			set
			{
				SetValue("LinkZone", value);
			}
		}


		/// <summary>
		/// Script zone.
		/// </summary>
		[DatabaseField]
		public string ScriptZone
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ScriptZone"), @"");
			}
			set
			{
				SetValue("ScriptZone", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with LayoutHeadSettings fields.
		/// </summary>
		[RegisterProperty]
		public LayoutHeadSettingsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with LayoutHeadSettings fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class LayoutHeadSettingsFields : AbstractHierarchicalObject<LayoutHeadSettingsFields>
		{
			/// <summary>
			/// The content item of type LayoutHeadSettings that is a target of the extended API.
			/// </summary>
			private readonly LayoutHeadSettings mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="LayoutHeadSettingsFields" /> class with the specified content item of type LayoutHeadSettings.
			/// </summary>
			/// <param name="instance">The content item of type LayoutHeadSettings that is a target of the extended API.</param>
			public LayoutHeadSettingsFields(LayoutHeadSettings instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// LayoutSettingsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.LayoutHeadSettingsID;
				}
				set
				{
					mInstance.LayoutHeadSettingsID = value;
				}
			}


			/// <summary>
			/// Meta data zone.
			/// </summary>
			public string MetaDataZone
			{
				get
				{
					return mInstance.MetaDataZone;
				}
				set
				{
					mInstance.MetaDataZone = value;
				}
			}


			/// <summary>
			/// Favicon type.
			/// </summary>
			public int FaviconType
			{
				get
				{
					return mInstance.FaviconType;
				}
				set
				{
					mInstance.FaviconType = value;
				}
			}


			/// <summary>
			/// Favicon link.
			/// </summary>
			public string FaviconLink
			{
				get
				{
					return mInstance.FaviconLink;
				}
				set
				{
					mInstance.FaviconLink = value;
				}
			}


			/// <summary>
			/// Favicon image.
			/// </summary>
			public string FaviconImage
			{
				get
				{
					return mInstance.FaviconImage;
				}
				set
				{
					mInstance.FaviconImage = value;
				}
			}


			/// <summary>
			/// Favicon image type.
			/// </summary>
			public string FaviconImageType
			{
				get
				{
					return mInstance.FaviconImageType;
				}
				set
				{
					mInstance.FaviconImageType = value;
				}
			}


			/// <summary>
			/// CSS/Link zone.
			/// </summary>
			public string LinkZone
			{
				get
				{
					return mInstance.LinkZone;
				}
				set
				{
					mInstance.LinkZone = value;
				}
			}


			/// <summary>
			/// Script zone.
			/// </summary>
			public string ScriptZone
			{
				get
				{
					return mInstance.ScriptZone;
				}
				set
				{
					mInstance.ScriptZone = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="LayoutHeadSettings" /> class.
		/// </summary>
		public LayoutHeadSettings() : base(CLASS_NAME)
		{
			mFields = new LayoutHeadSettingsFields(this);
		}

		#endregion
	}
}