//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.HXC;

[assembly: RegisterDocumentType(NavigationFolder.CLASS_NAME, typeof(NavigationFolder))]

namespace CMS.DocumentEngine.Types.HXC
{
	/// <summary>
	/// Represents a content item of type NavigationFolder.
	/// </summary>
	public partial class NavigationFolder : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "HXC.NavigationFolder";


		/// <summary>
		/// The instance of the class that provides extended API for working with NavigationFolder fields.
		/// </summary>
		private readonly NavigationFolderFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// NavigationFolderID.
		/// </summary>
		[DatabaseIDField]
		public int NavigationFolderID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("NavigationFolderID"), 0);
			}
			set
			{
				SetValue("NavigationFolderID", value);
			}
		}


		/// <summary>
		/// Element ID.
		/// </summary>
		[DatabaseField]
		public string ElementID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementID"), @"");
			}
			set
			{
				SetValue("ElementID", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with NavigationFolder fields.
		/// </summary>
		[RegisterProperty]
		public NavigationFolderFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with NavigationFolder fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class NavigationFolderFields : AbstractHierarchicalObject<NavigationFolderFields>
		{
			/// <summary>
			/// The content item of type NavigationFolder that is a target of the extended API.
			/// </summary>
			private readonly NavigationFolder mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="NavigationFolderFields" /> class with the specified content item of type NavigationFolder.
			/// </summary>
			/// <param name="instance">The content item of type NavigationFolder that is a target of the extended API.</param>
			public NavigationFolderFields(NavigationFolder instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// NavigationFolderID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.NavigationFolderID;
				}
				set
				{
					mInstance.NavigationFolderID = value;
				}
			}


			/// <summary>
			/// Element ID.
			/// </summary>
			public string ElementID
			{
				get
				{
					return mInstance.ElementID;
				}
				set
				{
					mInstance.ElementID = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="NavigationFolder" /> class.
		/// </summary>
		public NavigationFolder() : base(CLASS_NAME)
		{
			mFields = new NavigationFolderFields(this);
		}

		#endregion
	}
}