//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.HXC;

[assembly: RegisterDocumentType(StyleSheet.CLASS_NAME, typeof(StyleSheet))]

namespace CMS.DocumentEngine.Types.HXC
{
	/// <summary>
	/// Represents a content item of type StyleSheet.
	/// </summary>
	public partial class StyleSheet : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "HXC.StyleSheet";


		/// <summary>
		/// The instance of the class that provides extended API for working with StyleSheet fields.
		/// </summary>
		private readonly StyleSheetFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// HtmlCodeID.
		/// </summary>
		[DatabaseIDField]
		public int StyleSheetID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("StyleSheetID"), 0);
			}
			set
			{
				SetValue("StyleSheetID", value);
			}
		}


		/// <summary>
		/// Script.
		/// </summary>
		[DatabaseField]
		public string ScriptContent
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ScriptContent"), @"");
			}
			set
			{
				SetValue("ScriptContent", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with StyleSheet fields.
		/// </summary>
		[RegisterProperty]
		public StyleSheetFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with StyleSheet fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class StyleSheetFields : AbstractHierarchicalObject<StyleSheetFields>
		{
			/// <summary>
			/// The content item of type StyleSheet that is a target of the extended API.
			/// </summary>
			private readonly StyleSheet mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="StyleSheetFields" /> class with the specified content item of type StyleSheet.
			/// </summary>
			/// <param name="instance">The content item of type StyleSheet that is a target of the extended API.</param>
			public StyleSheetFields(StyleSheet instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// HtmlCodeID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.StyleSheetID;
				}
				set
				{
					mInstance.StyleSheetID = value;
				}
			}


			/// <summary>
			/// Script.
			/// </summary>
			public string ScriptContent
			{
				get
				{
					return mInstance.ScriptContent;
				}
				set
				{
					mInstance.ScriptContent = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="StyleSheet" /> class.
		/// </summary>
		public StyleSheet() : base(CLASS_NAME)
		{
			mFields = new StyleSheetFields(this);
		}

		#endregion
	}
}