//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using CMS.CustomTables.Types.Customtable;

[assembly: RegisterCustomTable(Plearn_AuthorItem.CLASS_NAME, typeof(Plearn_AuthorItem))]

namespace CMS.CustomTables.Types.Customtable
{
	/// <summary>
	/// Represents a content item of type Plearn_AuthorItem.
	/// </summary>
	public partial class Plearn_AuthorItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "customtable.Plearn_Author";


		/// <summary>
		/// The instance of the class that provides extended API for working with Plearn_AuthorItem fields.
		/// </summary>
		private readonly Plearn_AuthorItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Code.
		/// </summary>
		[DatabaseField]
		public string Code
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Code"), @"");
			}
			set
			{
				SetValue("Code", value);
			}
		}


		/// <summary>
		/// Author name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Author profile.
		/// </summary>
		[DatabaseField]
		public string ProfileImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ProfileImage"), @"");
			}
			set
			{
				SetValue("ProfileImage", value);
			}
		}


		/// <summary>
		/// Position.
		/// </summary>
		[DatabaseField]
		public string Position
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Position"), @"");
			}
			set
			{
				SetValue("Position", value);
			}
		}


		/// <summary>
		/// Company.
		/// </summary>
		[DatabaseField]
		public string Company
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Company"), @"");
			}
			set
			{
				SetValue("Company", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Plearn_AuthorItem fields.
		/// </summary>
		[RegisterProperty]
		public Plearn_AuthorItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Plearn_AuthorItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class Plearn_AuthorItemFields : AbstractHierarchicalObject<Plearn_AuthorItemFields>
		{
			/// <summary>
			/// The content item of type Plearn_AuthorItem that is a target of the extended API.
			/// </summary>
			private readonly Plearn_AuthorItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="Plearn_AuthorItemFields" /> class with the specified content item of type Plearn_AuthorItem.
			/// </summary>
			/// <param name="instance">The content item of type Plearn_AuthorItem that is a target of the extended API.</param>
			public Plearn_AuthorItemFields(Plearn_AuthorItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Code.
			/// </summary>
			public string Code
			{
				get
				{
					return mInstance.Code;
				}
				set
				{
					mInstance.Code = value;
				}
			}


			/// <summary>
			/// Author name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Author profile.
			/// </summary>
			public string ProfileImage
			{
				get
				{
					return mInstance.ProfileImage;
				}
				set
				{
					mInstance.ProfileImage = value;
				}
			}


			/// <summary>
			/// Position.
			/// </summary>
			public string Position
			{
				get
				{
					return mInstance.Position;
				}
				set
				{
					mInstance.Position = value;
				}
			}


			/// <summary>
			/// Company.
			/// </summary>
			public string Company
			{
				get
				{
					return mInstance.Company;
				}
				set
				{
					mInstance.Company = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Plearn_AuthorItem" /> class.
		/// </summary>
		public Plearn_AuthorItem() : base(CLASS_NAME)
		{
			mFields = new Plearn_AuthorItemFields(this);
		}

		#endregion
	}
}