//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.BAY;

[assembly: RegisterDocumentType(BaseComponent.CLASS_NAME, typeof(BaseComponent))]

namespace CMS.DocumentEngine.Types.BAY
{
	/// <summary>
	/// Represents a content item of type BaseComponent.
	/// </summary>
	public partial class BaseComponent : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BAY.BaseComponent";


		/// <summary>
		/// The instance of the class that provides extended API for working with BaseComponent fields.
		/// </summary>
		private readonly BaseComponentFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// KrungsriBaseComponentID.
		/// </summary>
		[DatabaseIDField]
		public int BaseComponentID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BaseComponentID"), 0);
			}
			set
			{
				SetValue("BaseComponentID", value);
			}
		}


		/// <summary>
		/// Element ID.
		/// </summary>
		[DatabaseField]
		public string ElementID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementID"), @"");
			}
			set
			{
				SetValue("ElementID", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BaseComponent fields.
		/// </summary>
		[RegisterProperty]
		public BaseComponentFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BaseComponent fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BaseComponentFields : AbstractHierarchicalObject<BaseComponentFields>
		{
			/// <summary>
			/// The content item of type BaseComponent that is a target of the extended API.
			/// </summary>
			private readonly BaseComponent mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BaseComponentFields" /> class with the specified content item of type BaseComponent.
			/// </summary>
			/// <param name="instance">The content item of type BaseComponent that is a target of the extended API.</param>
			public BaseComponentFields(BaseComponent instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// KrungsriBaseComponentID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BaseComponentID;
				}
				set
				{
					mInstance.BaseComponentID = value;
				}
			}


			/// <summary>
			/// Element ID.
			/// </summary>
			public string ElementID
			{
				get
				{
					return mInstance.ElementID;
				}
				set
				{
					mInstance.ElementID = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BaseComponent" /> class.
		/// </summary>
		public BaseComponent() : base(CLASS_NAME)
		{
			mFields = new BaseComponentFields(this);
		}

		#endregion
	}
}