//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.BAY;

[assembly: RegisterDocumentType(ImageBanner480.CLASS_NAME, typeof(ImageBanner480))]

namespace CMS.DocumentEngine.Types.BAY
{
	/// <summary>
	/// Represents a content item of type ImageBanner480.
	/// </summary>
	public partial class ImageBanner480 : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BAY.ImageBanner480";


		/// <summary>
		/// The instance of the class that provides extended API for working with ImageBanner480 fields.
		/// </summary>
		private readonly ImageBanner480Fields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BannerImage360ID.
		/// </summary>
		[DatabaseIDField]
		public int ImageBanner480ID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ImageBanner480ID"), 0);
			}
			set
			{
				SetValue("ImageBanner480ID", value);
			}
		}


		/// <summary>
		/// Image desktop (1920x480).
		/// </summary>
		[DatabaseField]
		public string ImageDesktop
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ImageDesktop"), @"");
			}
			set
			{
				SetValue("ImageDesktop", value);
			}
		}


		/// <summary>
		/// Image mobile (770x520).
		/// </summary>
		[DatabaseField]
		public string ImageMobile
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ImageMobile"), @"");
			}
			set
			{
				SetValue("ImageMobile", value);
			}
		}


		/// <summary>
		/// Image alt.
		/// </summary>
		[DatabaseField]
		public string ImageAlt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ImageAlt"), @"");
			}
			set
			{
				SetValue("ImageAlt", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Title font color.
		/// </summary>
		[DatabaseField]
		public string TitleFontColor
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TitleFontColor"), @"");
			}
			set
			{
				SetValue("TitleFontColor", value);
			}
		}


		/// <summary>
		/// Subtitle.
		/// </summary>
		[DatabaseField]
		public string Subtitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Subtitle"), @"");
			}
			set
			{
				SetValue("Subtitle", value);
			}
		}


		/// <summary>
		/// Subtitle font color.
		/// </summary>
		[DatabaseField]
		public string SubtitleFontColor
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SubtitleFontColor"), @"");
			}
			set
			{
				SetValue("SubtitleFontColor", value);
			}
		}


		/// <summary>
		/// Text alignment.
		/// </summary>
		[DatabaseField]
		public string TextAlignment
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TextAlignment"), @"");
			}
			set
			{
				SetValue("TextAlignment", value);
			}
		}


		/// <summary>
		/// Has button.
		/// </summary>
		[DatabaseField]
		public bool HasButton
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("HasButton"), false);
			}
			set
			{
				SetValue("HasButton", value);
			}
		}


		/// <summary>
		/// Button text.
		/// </summary>
		[DatabaseField]
		public string ButtonText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ButtonText"), @"");
			}
			set
			{
				SetValue("ButtonText", value);
			}
		}


		/// <summary>
		/// Botton color.
		/// </summary>
		[DatabaseField]
		public string BottonColor
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BottonColor"), @"");
			}
			set
			{
				SetValue("BottonColor", value);
			}
		}


		/// <summary>
		/// Button alignment.
		/// </summary>
		[DatabaseField]
		public string ButtonAlignment
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ButtonAlignment"), @"");
			}
			set
			{
				SetValue("ButtonAlignment", value);
			}
		}


		/// <summary>
		/// Link type.
		/// </summary>
		[DatabaseField]
		public int LinkType
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("LinkType"), 2);
			}
			set
			{
				SetValue("LinkType", value);
			}
		}


		/// <summary>
		/// Link page.
		/// </summary>
		[DatabaseField]
		public Guid LinkPageNodeGuid
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("LinkPageNodeGuid"), Guid.Empty);
			}
			set
			{
				SetValue("LinkPageNodeGuid", value);
			}
		}


		/// <summary>
		/// Link URL.
		/// </summary>
		[DatabaseField]
		public string LinkUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkUrl"), @"");
			}
			set
			{
				SetValue("LinkUrl", value);
			}
		}


		/// <summary>
		/// Link target.
		/// </summary>
		[DatabaseField]
		public string LinkTarget
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkTarget"), @"");
			}
			set
			{
				SetValue("LinkTarget", value);
			}
		}


		/// <summary>
		/// Link alt.
		/// </summary>
		[DatabaseField]
		public string LinkAlt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkAlt"), @"");
			}
			set
			{
				SetValue("LinkAlt", value);
			}
		}


		/// <summary>
		/// Link CSS.
		/// </summary>
		[DatabaseField]
		public string LinkCss
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkCss"), @"");
			}
			set
			{
				SetValue("LinkCss", value);
			}
		}


		/// <summary>
		/// Link on-click (Javascript).
		/// </summary>
		[DatabaseField]
		public string LinkOnClick
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkOnClick"), @"");
			}
			set
			{
				SetValue("LinkOnClick", value);
			}
		}


		/// <summary>
		/// Enable.
		/// </summary>
		[DatabaseField]
		public bool GAEnable
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("GAEnable"), false);
			}
			set
			{
				SetValue("GAEnable", value);
			}
		}


		/// <summary>
		/// Event code.
		/// </summary>
		[DatabaseField]
		public string GAEventCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GAEventCode"), @"");
			}
			set
			{
				SetValue("GAEventCode", value);
			}
		}


		/// <summary>
		/// Category.
		/// </summary>
		[DatabaseField]
		public string GACategory
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GACategory"), @"");
			}
			set
			{
				SetValue("GACategory", value);
			}
		}


		/// <summary>
		/// Action.
		/// </summary>
		[DatabaseField]
		public string GAAction
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GAAction"), @"");
			}
			set
			{
				SetValue("GAAction", value);
			}
		}


		/// <summary>
		/// Label.
		/// </summary>
		[DatabaseField]
		public string GALabel
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GALabel"), @"");
			}
			set
			{
				SetValue("GALabel", value);
			}
		}


		/// <summary>
		/// Element ID.
		/// </summary>
		[DatabaseField]
		public string ElementID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementID"), @"");
			}
			set
			{
				SetValue("ElementID", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ImageBanner480 fields.
		/// </summary>
		[RegisterProperty]
		public ImageBanner480Fields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ImageBanner480 fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ImageBanner480Fields : AbstractHierarchicalObject<ImageBanner480Fields>
		{
			/// <summary>
			/// The content item of type ImageBanner480 that is a target of the extended API.
			/// </summary>
			private readonly ImageBanner480 mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ImageBanner480Fields" /> class with the specified content item of type ImageBanner480.
			/// </summary>
			/// <param name="instance">The content item of type ImageBanner480 that is a target of the extended API.</param>
			public ImageBanner480Fields(ImageBanner480 instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BannerImage360ID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ImageBanner480ID;
				}
				set
				{
					mInstance.ImageBanner480ID = value;
				}
			}


			/// <summary>
			/// Image desktop (1920x480).
			/// </summary>
			public string ImageDesktop
			{
				get
				{
					return mInstance.ImageDesktop;
				}
				set
				{
					mInstance.ImageDesktop = value;
				}
			}


			/// <summary>
			/// Image mobile (770x520).
			/// </summary>
			public string ImageMobile
			{
				get
				{
					return mInstance.ImageMobile;
				}
				set
				{
					mInstance.ImageMobile = value;
				}
			}


			/// <summary>
			/// Image alt.
			/// </summary>
			public string ImageAlt
			{
				get
				{
					return mInstance.ImageAlt;
				}
				set
				{
					mInstance.ImageAlt = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Title font color.
			/// </summary>
			public string TitleFontColor
			{
				get
				{
					return mInstance.TitleFontColor;
				}
				set
				{
					mInstance.TitleFontColor = value;
				}
			}


			/// <summary>
			/// Subtitle.
			/// </summary>
			public string Subtitle
			{
				get
				{
					return mInstance.Subtitle;
				}
				set
				{
					mInstance.Subtitle = value;
				}
			}


			/// <summary>
			/// Subtitle font color.
			/// </summary>
			public string SubtitleFontColor
			{
				get
				{
					return mInstance.SubtitleFontColor;
				}
				set
				{
					mInstance.SubtitleFontColor = value;
				}
			}


			/// <summary>
			/// Text alignment.
			/// </summary>
			public string TextAlignment
			{
				get
				{
					return mInstance.TextAlignment;
				}
				set
				{
					mInstance.TextAlignment = value;
				}
			}


			/// <summary>
			/// Has button.
			/// </summary>
			public bool HasButton
			{
				get
				{
					return mInstance.HasButton;
				}
				set
				{
					mInstance.HasButton = value;
				}
			}


			/// <summary>
			/// Button text.
			/// </summary>
			public string ButtonText
			{
				get
				{
					return mInstance.ButtonText;
				}
				set
				{
					mInstance.ButtonText = value;
				}
			}


			/// <summary>
			/// Botton color.
			/// </summary>
			public string BottonColor
			{
				get
				{
					return mInstance.BottonColor;
				}
				set
				{
					mInstance.BottonColor = value;
				}
			}


			/// <summary>
			/// Button alignment.
			/// </summary>
			public string ButtonAlignment
			{
				get
				{
					return mInstance.ButtonAlignment;
				}
				set
				{
					mInstance.ButtonAlignment = value;
				}
			}


			/// <summary>
			/// Link type.
			/// </summary>
			public int LinkType
			{
				get
				{
					return mInstance.LinkType;
				}
				set
				{
					mInstance.LinkType = value;
				}
			}


			/// <summary>
			/// Link page.
			/// </summary>
			public Guid LinkPageNodeGuid
			{
				get
				{
					return mInstance.LinkPageNodeGuid;
				}
				set
				{
					mInstance.LinkPageNodeGuid = value;
				}
			}


			/// <summary>
			/// Link URL.
			/// </summary>
			public string LinkUrl
			{
				get
				{
					return mInstance.LinkUrl;
				}
				set
				{
					mInstance.LinkUrl = value;
				}
			}


			/// <summary>
			/// Link target.
			/// </summary>
			public string LinkTarget
			{
				get
				{
					return mInstance.LinkTarget;
				}
				set
				{
					mInstance.LinkTarget = value;
				}
			}


			/// <summary>
			/// Link alt.
			/// </summary>
			public string LinkAlt
			{
				get
				{
					return mInstance.LinkAlt;
				}
				set
				{
					mInstance.LinkAlt = value;
				}
			}


			/// <summary>
			/// Link CSS.
			/// </summary>
			public string LinkCss
			{
				get
				{
					return mInstance.LinkCss;
				}
				set
				{
					mInstance.LinkCss = value;
				}
			}


			/// <summary>
			/// Link on-click (Javascript).
			/// </summary>
			public string LinkOnClick
			{
				get
				{
					return mInstance.LinkOnClick;
				}
				set
				{
					mInstance.LinkOnClick = value;
				}
			}


			/// <summary>
			/// Enable.
			/// </summary>
			public bool GAEnable
			{
				get
				{
					return mInstance.GAEnable;
				}
				set
				{
					mInstance.GAEnable = value;
				}
			}


			/// <summary>
			/// Event code.
			/// </summary>
			public string GAEventCode
			{
				get
				{
					return mInstance.GAEventCode;
				}
				set
				{
					mInstance.GAEventCode = value;
				}
			}


			/// <summary>
			/// Category.
			/// </summary>
			public string GACategory
			{
				get
				{
					return mInstance.GACategory;
				}
				set
				{
					mInstance.GACategory = value;
				}
			}


			/// <summary>
			/// Action.
			/// </summary>
			public string GAAction
			{
				get
				{
					return mInstance.GAAction;
				}
				set
				{
					mInstance.GAAction = value;
				}
			}


			/// <summary>
			/// Label.
			/// </summary>
			public string GALabel
			{
				get
				{
					return mInstance.GALabel;
				}
				set
				{
					mInstance.GALabel = value;
				}
			}


			/// <summary>
			/// Element ID.
			/// </summary>
			public string ElementID
			{
				get
				{
					return mInstance.ElementID;
				}
				set
				{
					mInstance.ElementID = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ImageBanner480" /> class.
		/// </summary>
		public ImageBanner480() : base(CLASS_NAME)
		{
			mFields = new ImageBanner480Fields(this);
		}

		#endregion
	}
}