//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.BAY;

[assembly: RegisterDocumentType(ImageIcon.CLASS_NAME, typeof(ImageIcon))]

namespace CMS.DocumentEngine.Types.BAY
{
	/// <summary>
	/// Represents a content item of type ImageIcon.
	/// </summary>
	public partial class ImageIcon : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BAY.ImageIcon";


		/// <summary>
		/// The instance of the class that provides extended API for working with ImageIcon fields.
		/// </summary>
		private readonly ImageIconFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BannerImage360ID.
		/// </summary>
		[DatabaseIDField]
		public int ImageIconID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ImageIconID"), 0);
			}
			set
			{
				SetValue("ImageIconID", value);
			}
		}


		/// <summary>
		/// Image.
		/// </summary>
		[DatabaseField]
		public string Image
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Image"), @"");
			}
			set
			{
				SetValue("Image", value);
			}
		}


		/// <summary>
		/// Image alt.
		/// </summary>
		[DatabaseField]
		public string ImageAlt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ImageAlt"), @"");
			}
			set
			{
				SetValue("ImageAlt", value);
			}
		}


		/// <summary>
		/// Element ID.
		/// </summary>
		[DatabaseField]
		public string ElementID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementID"), @"");
			}
			set
			{
				SetValue("ElementID", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ImageIcon fields.
		/// </summary>
		[RegisterProperty]
		public ImageIconFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ImageIcon fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ImageIconFields : AbstractHierarchicalObject<ImageIconFields>
		{
			/// <summary>
			/// The content item of type ImageIcon that is a target of the extended API.
			/// </summary>
			private readonly ImageIcon mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ImageIconFields" /> class with the specified content item of type ImageIcon.
			/// </summary>
			/// <param name="instance">The content item of type ImageIcon that is a target of the extended API.</param>
			public ImageIconFields(ImageIcon instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BannerImage360ID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ImageIconID;
				}
				set
				{
					mInstance.ImageIconID = value;
				}
			}


			/// <summary>
			/// Image.
			/// </summary>
			public string Image
			{
				get
				{
					return mInstance.Image;
				}
				set
				{
					mInstance.Image = value;
				}
			}


			/// <summary>
			/// Image alt.
			/// </summary>
			public string ImageAlt
			{
				get
				{
					return mInstance.ImageAlt;
				}
				set
				{
					mInstance.ImageAlt = value;
				}
			}


			/// <summary>
			/// Element ID.
			/// </summary>
			public string ElementID
			{
				get
				{
					return mInstance.ElementID;
				}
				set
				{
					mInstance.ElementID = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ImageIcon" /> class.
		/// </summary>
		public ImageIcon() : base(CLASS_NAME)
		{
			mFields = new ImageIconFields(this);
		}

		#endregion
	}
}