//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.BAY;

[assembly: RegisterDocumentType(MediaFile.CLASS_NAME, typeof(MediaFile))]

namespace CMS.DocumentEngine.Types.BAY
{
	/// <summary>
	/// Represents a content item of type MediaFile.
	/// </summary>
	public partial class MediaFile : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BAY.MediaFile";


		/// <summary>
		/// The instance of the class that provides extended API for working with MediaFile fields.
		/// </summary>
		private readonly MediaFileFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// MediaFileID.
		/// </summary>
		[DatabaseIDField]
		public int MediaFileID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("MediaFileID"), 0);
			}
			set
			{
				SetValue("MediaFileID", value);
			}
		}


		/// <summary>
		/// Data source.
		/// </summary>
		[DatabaseField]
		public int DataSource
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("DataSource"), 0);
			}
			set
			{
				SetValue("DataSource", value);
			}
		}


		/// <summary>
		/// Media file URL.
		/// </summary>
		[DatabaseField]
		public string FileUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FileUrl"), @"");
			}
			set
			{
				SetValue("FileUrl", value);
			}
		}


		/// <summary>
		/// File upload.
		/// </summary>
		[DatabaseField]
		public Guid FileUpload
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("FileUpload"), Guid.Empty);
			}
			set
			{
				SetValue("FileUpload", value);
			}
		}


		/// <summary>
		/// Enable.
		/// </summary>
		[DatabaseField]
		public bool GAEnable
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("GAEnable"), false);
			}
			set
			{
				SetValue("GAEnable", value);
			}
		}


		/// <summary>
		/// Event code.
		/// </summary>
		[DatabaseField]
		public string GAEventCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GAEventCode"), @"");
			}
			set
			{
				SetValue("GAEventCode", value);
			}
		}


		/// <summary>
		/// Category.
		/// </summary>
		[DatabaseField]
		public string GACategory
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GACategory"), @"");
			}
			set
			{
				SetValue("GACategory", value);
			}
		}


		/// <summary>
		/// Action.
		/// </summary>
		[DatabaseField]
		public string GAAction
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GAAction"), @"");
			}
			set
			{
				SetValue("GAAction", value);
			}
		}


		/// <summary>
		/// Label.
		/// </summary>
		[DatabaseField]
		public string GALabel
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GALabel"), @"");
			}
			set
			{
				SetValue("GALabel", value);
			}
		}


		/// <summary>
		/// Element ID.
		/// </summary>
		[DatabaseField]
		public string ElementID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementID"), @"");
			}
			set
			{
				SetValue("ElementID", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with MediaFile fields.
		/// </summary>
		[RegisterProperty]
		public MediaFileFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with MediaFile fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class MediaFileFields : AbstractHierarchicalObject<MediaFileFields>
		{
			/// <summary>
			/// The content item of type MediaFile that is a target of the extended API.
			/// </summary>
			private readonly MediaFile mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="MediaFileFields" /> class with the specified content item of type MediaFile.
			/// </summary>
			/// <param name="instance">The content item of type MediaFile that is a target of the extended API.</param>
			public MediaFileFields(MediaFile instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// MediaFileID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.MediaFileID;
				}
				set
				{
					mInstance.MediaFileID = value;
				}
			}


			/// <summary>
			/// Data source.
			/// </summary>
			public int DataSource
			{
				get
				{
					return mInstance.DataSource;
				}
				set
				{
					mInstance.DataSource = value;
				}
			}


			/// <summary>
			/// Media file URL.
			/// </summary>
			public string FileUrl
			{
				get
				{
					return mInstance.FileUrl;
				}
				set
				{
					mInstance.FileUrl = value;
				}
			}


			/// <summary>
			/// File upload.
			/// </summary>
			public DocumentAttachment FileUpload
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("FileUpload");
				}
			}


			/// <summary>
			/// Enable.
			/// </summary>
			public bool GAEnable
			{
				get
				{
					return mInstance.GAEnable;
				}
				set
				{
					mInstance.GAEnable = value;
				}
			}


			/// <summary>
			/// Event code.
			/// </summary>
			public string GAEventCode
			{
				get
				{
					return mInstance.GAEventCode;
				}
				set
				{
					mInstance.GAEventCode = value;
				}
			}


			/// <summary>
			/// Category.
			/// </summary>
			public string GACategory
			{
				get
				{
					return mInstance.GACategory;
				}
				set
				{
					mInstance.GACategory = value;
				}
			}


			/// <summary>
			/// Action.
			/// </summary>
			public string GAAction
			{
				get
				{
					return mInstance.GAAction;
				}
				set
				{
					mInstance.GAAction = value;
				}
			}


			/// <summary>
			/// Label.
			/// </summary>
			public string GALabel
			{
				get
				{
					return mInstance.GALabel;
				}
				set
				{
					mInstance.GALabel = value;
				}
			}


			/// <summary>
			/// Element ID.
			/// </summary>
			public string ElementID
			{
				get
				{
					return mInstance.ElementID;
				}
				set
				{
					mInstance.ElementID = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="MediaFile" /> class.
		/// </summary>
		public MediaFile() : base(CLASS_NAME)
		{
			mFields = new MediaFileFields(this);
		}

		#endregion
	}
}