//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.BAY;

[assembly: RegisterDocumentType(Navigation.CLASS_NAME, typeof(Navigation))]

namespace CMS.DocumentEngine.Types.BAY
{
	/// <summary>
	/// Represents a content item of type Navigation.
	/// </summary>
	public partial class Navigation : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BAY.Navigation";


		/// <summary>
		/// The instance of the class that provides extended API for working with Navigation fields.
		/// </summary>
		private readonly NavigationFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// NavigationID.
		/// </summary>
		[DatabaseIDField]
		public int NavigationID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("NavigationID"), 0);
			}
			set
			{
				SetValue("NavigationID", value);
			}
		}


		/// <summary>
		/// Link type.
		/// </summary>
		[DatabaseField]
		public int LinkType
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("LinkType"), 2);
			}
			set
			{
				SetValue("LinkType", value);
			}
		}


		/// <summary>
		/// Link page.
		/// </summary>
		[DatabaseField]
		public Guid LinkPageNodeGuid
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("LinkPageNodeGuid"), Guid.Empty);
			}
			set
			{
				SetValue("LinkPageNodeGuid", value);
			}
		}


		/// <summary>
		/// Link URL.
		/// </summary>
		[DatabaseField]
		public string LinkUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkUrl"), @"");
			}
			set
			{
				SetValue("LinkUrl", value);
			}
		}


		/// <summary>
		/// Link target.
		/// </summary>
		[DatabaseField]
		public string LinkTarget
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkTarget"), @"");
			}
			set
			{
				SetValue("LinkTarget", value);
			}
		}


		/// <summary>
		/// Link alt.
		/// </summary>
		[DatabaseField]
		public string LinkAlt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkAlt"), @"");
			}
			set
			{
				SetValue("LinkAlt", value);
			}
		}


		/// <summary>
		/// Link CSS.
		/// </summary>
		[DatabaseField]
		public string LinkCss
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkCss"), @"");
			}
			set
			{
				SetValue("LinkCss", value);
			}
		}


		/// <summary>
		/// Link on-click (Javascript).
		/// </summary>
		[DatabaseField]
		public string LinkOnClick
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkOnClick"), @"");
			}
			set
			{
				SetValue("LinkOnClick", value);
			}
		}


		/// <summary>
		/// Enable.
		/// </summary>
		[DatabaseField]
		public bool GAEnable
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("GAEnable"), false);
			}
			set
			{
				SetValue("GAEnable", value);
			}
		}


		/// <summary>
		/// Event code.
		/// </summary>
		[DatabaseField]
		public string GAEventCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GAEventCode"), @"");
			}
			set
			{
				SetValue("GAEventCode", value);
			}
		}


		/// <summary>
		/// Category.
		/// </summary>
		[DatabaseField]
		public string GACategory
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GACategory"), @"");
			}
			set
			{
				SetValue("GACategory", value);
			}
		}


		/// <summary>
		/// Action.
		/// </summary>
		[DatabaseField]
		public string GAAction
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GAAction"), @"");
			}
			set
			{
				SetValue("GAAction", value);
			}
		}


		/// <summary>
		/// Label.
		/// </summary>
		[DatabaseField]
		public string GALabel
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GALabel"), @"");
			}
			set
			{
				SetValue("GALabel", value);
			}
		}


		/// <summary>
		/// Navigation name.
		/// </summary>
		[DatabaseField]
		public string NavigationName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NavigationName"), @"");
			}
			set
			{
				SetValue("NavigationName", value);
			}
		}


		/// <summary>
		/// Whether or not the Navigation Item should automatically build itself off of the selected page, or if you want to manually enter in the information.
		/// </summary>
		[DatabaseField]
		public int NavigationType
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("NavigationType"), 0);
			}
			set
			{
				SetValue("NavigationType", value);
			}
		}


		/// <summary>
		/// Can select a page, the navigation will be based on this page's Title and Url.
		/// </summary>
		[DatabaseField]
		public Guid NavigationPageNodeGuid
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("NavigationPageNodeGuid"), Guid.Empty);
			}
			set
			{
				SetValue("NavigationPageNodeGuid", value);
			}
		}


		/// <summary>
		/// Can be HTML (icons and stuff), but be sure to make it valid HTML if you do.
		/// </summary>
		[DatabaseField]
		public string NavigationLinkText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NavigationLinkText"), @"");
			}
			set
			{
				SetValue("NavigationLinkText", value);
			}
		}


		/// <summary>
		/// Nav Link.
		/// </summary>
		[DatabaseField]
		public string NavigationLinkUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NavigationLinkUrl"), @"");
			}
			set
			{
				SetValue("NavigationLinkUrl", value);
			}
		}


		/// <summary>
		/// Link target.
		/// </summary>
		[DatabaseField]
		public string NavigationLinkTarget
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NavigationLinkTarget"), @"_self");
			}
			set
			{
				SetValue("NavigationLinkTarget", value);
			}
		}


		/// <summary>
		/// Descriptive text for on hover and for screen readers.
		/// </summary>
		[DatabaseField]
		public string NavigationLinkAlt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NavigationLinkAlt"), @"");
			}
			set
			{
				SetValue("NavigationLinkAlt", value);
			}
		}


		/// <summary>
		/// Optional On click for the link.
		/// </summary>
		[DatabaseField]
		public string NavigationLinkOnClick
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NavigationLinkOnClick"), @"");
			}
			set
			{
				SetValue("NavigationLinkOnClick", value);
			}
		}


		/// <summary>
		/// Optional CSS Class applied to the navigation item.
		/// </summary>
		[DatabaseField]
		public string NavigationLinkCSS
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NavigationLinkCSS"), @"");
			}
			set
			{
				SetValue("NavigationLinkCSS", value);
			}
		}


		/// <summary>
		/// Element ID.
		/// </summary>
		[DatabaseField]
		public string ElementID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementID"), @"");
			}
			set
			{
				SetValue("ElementID", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Navigation fields.
		/// </summary>
		[RegisterProperty]
		public NavigationFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Navigation fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class NavigationFields : AbstractHierarchicalObject<NavigationFields>
		{
			/// <summary>
			/// The content item of type Navigation that is a target of the extended API.
			/// </summary>
			private readonly Navigation mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="NavigationFields" /> class with the specified content item of type Navigation.
			/// </summary>
			/// <param name="instance">The content item of type Navigation that is a target of the extended API.</param>
			public NavigationFields(Navigation instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// NavigationID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.NavigationID;
				}
				set
				{
					mInstance.NavigationID = value;
				}
			}


			/// <summary>
			/// Link type.
			/// </summary>
			public int LinkType
			{
				get
				{
					return mInstance.LinkType;
				}
				set
				{
					mInstance.LinkType = value;
				}
			}


			/// <summary>
			/// Link page.
			/// </summary>
			public Guid LinkPageNodeGuid
			{
				get
				{
					return mInstance.LinkPageNodeGuid;
				}
				set
				{
					mInstance.LinkPageNodeGuid = value;
				}
			}


			/// <summary>
			/// Link URL.
			/// </summary>
			public string LinkUrl
			{
				get
				{
					return mInstance.LinkUrl;
				}
				set
				{
					mInstance.LinkUrl = value;
				}
			}


			/// <summary>
			/// Link target.
			/// </summary>
			public string LinkTarget
			{
				get
				{
					return mInstance.LinkTarget;
				}
				set
				{
					mInstance.LinkTarget = value;
				}
			}


			/// <summary>
			/// Link alt.
			/// </summary>
			public string LinkAlt
			{
				get
				{
					return mInstance.LinkAlt;
				}
				set
				{
					mInstance.LinkAlt = value;
				}
			}


			/// <summary>
			/// Link CSS.
			/// </summary>
			public string LinkCss
			{
				get
				{
					return mInstance.LinkCss;
				}
				set
				{
					mInstance.LinkCss = value;
				}
			}


			/// <summary>
			/// Link on-click (Javascript).
			/// </summary>
			public string LinkOnClick
			{
				get
				{
					return mInstance.LinkOnClick;
				}
				set
				{
					mInstance.LinkOnClick = value;
				}
			}


			/// <summary>
			/// Enable.
			/// </summary>
			public bool GAEnable
			{
				get
				{
					return mInstance.GAEnable;
				}
				set
				{
					mInstance.GAEnable = value;
				}
			}


			/// <summary>
			/// Event code.
			/// </summary>
			public string GAEventCode
			{
				get
				{
					return mInstance.GAEventCode;
				}
				set
				{
					mInstance.GAEventCode = value;
				}
			}


			/// <summary>
			/// Category.
			/// </summary>
			public string GACategory
			{
				get
				{
					return mInstance.GACategory;
				}
				set
				{
					mInstance.GACategory = value;
				}
			}


			/// <summary>
			/// Action.
			/// </summary>
			public string GAAction
			{
				get
				{
					return mInstance.GAAction;
				}
				set
				{
					mInstance.GAAction = value;
				}
			}


			/// <summary>
			/// Label.
			/// </summary>
			public string GALabel
			{
				get
				{
					return mInstance.GALabel;
				}
				set
				{
					mInstance.GALabel = value;
				}
			}


			/// <summary>
			/// Navigation name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.NavigationName;
				}
				set
				{
					mInstance.NavigationName = value;
				}
			}


			/// <summary>
			/// Whether or not the Navigation Item should automatically build itself off of the selected page, or if you want to manually enter in the information.
			/// </summary>
			public int Type
			{
				get
				{
					return mInstance.NavigationType;
				}
				set
				{
					mInstance.NavigationType = value;
				}
			}


			/// <summary>
			/// Can select a page, the navigation will be based on this page's Title and Url.
			/// </summary>
			public Guid PageNodeGuid
			{
				get
				{
					return mInstance.NavigationPageNodeGuid;
				}
				set
				{
					mInstance.NavigationPageNodeGuid = value;
				}
			}


			/// <summary>
			/// Can be HTML (icons and stuff), but be sure to make it valid HTML if you do.
			/// </summary>
			public string LinkText
			{
				get
				{
					return mInstance.NavigationLinkText;
				}
				set
				{
					mInstance.NavigationLinkText = value;
				}
			}


			/// <summary>
			/// Nav Link.
			/// </summary>
			public string LinkUrl1
			{
				get
				{
					return mInstance.NavigationLinkUrl;
				}
				set
				{
					mInstance.NavigationLinkUrl = value;
				}
			}


			/// <summary>
			/// Link target.
			/// </summary>
			public string LinkTarget1
			{
				get
				{
					return mInstance.NavigationLinkTarget;
				}
				set
				{
					mInstance.NavigationLinkTarget = value;
				}
			}


			/// <summary>
			/// Descriptive text for on hover and for screen readers.
			/// </summary>
			public string LinkAlt1
			{
				get
				{
					return mInstance.NavigationLinkAlt;
				}
				set
				{
					mInstance.NavigationLinkAlt = value;
				}
			}


			/// <summary>
			/// Optional On click for the link.
			/// </summary>
			public string LinkOnClick1
			{
				get
				{
					return mInstance.NavigationLinkOnClick;
				}
				set
				{
					mInstance.NavigationLinkOnClick = value;
				}
			}


			/// <summary>
			/// Optional CSS Class applied to the navigation item.
			/// </summary>
			public string LinkCSS
			{
				get
				{
					return mInstance.NavigationLinkCSS;
				}
				set
				{
					mInstance.NavigationLinkCSS = value;
				}
			}


			/// <summary>
			/// Element ID.
			/// </summary>
			public string ElementID
			{
				get
				{
					return mInstance.ElementID;
				}
				set
				{
					mInstance.ElementID = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Navigation" /> class.
		/// </summary>
		public Navigation() : base(CLASS_NAME)
		{
			mFields = new NavigationFields(this);
		}

		#endregion
	}
}