//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.BAY;

[assembly: RegisterDocumentType(PopupContent.CLASS_NAME, typeof(PopupContent))]

namespace CMS.DocumentEngine.Types.BAY
{
	/// <summary>
	/// Represents a content item of type PopupContent.
	/// </summary>
	public partial class PopupContent : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BAY.PopupContent";


		/// <summary>
		/// The instance of the class that provides extended API for working with PopupContent fields.
		/// </summary>
		private readonly PopupContentFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// AccordionContentID.
		/// </summary>
		[DatabaseIDField]
		public int PopupContentID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PopupContentID"), 0);
			}
			set
			{
				SetValue("PopupContentID", value);
			}
		}


		/// <summary>
		/// Content header.
		/// </summary>
		[DatabaseField]
		public string ContentHeader
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContentHeader"), @"");
			}
			set
			{
				SetValue("ContentHeader", value);
			}
		}


		/// <summary>
		/// Enable.
		/// </summary>
		[DatabaseField]
		public bool GAEnable
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("GAEnable"), false);
			}
			set
			{
				SetValue("GAEnable", value);
			}
		}


		/// <summary>
		/// Event code.
		/// </summary>
		[DatabaseField]
		public string GAEventCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GAEventCode"), @"");
			}
			set
			{
				SetValue("GAEventCode", value);
			}
		}


		/// <summary>
		/// Category.
		/// </summary>
		[DatabaseField]
		public string GACategory
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GACategory"), @"");
			}
			set
			{
				SetValue("GACategory", value);
			}
		}


		/// <summary>
		/// Action.
		/// </summary>
		[DatabaseField]
		public string GAAction
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GAAction"), @"");
			}
			set
			{
				SetValue("GAAction", value);
			}
		}


		/// <summary>
		/// Label.
		/// </summary>
		[DatabaseField]
		public string GALabel
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GALabel"), @"");
			}
			set
			{
				SetValue("GALabel", value);
			}
		}


		/// <summary>
		/// Element ID.
		/// </summary>
		[DatabaseField]
		public string ElementID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementID"), @"");
			}
			set
			{
				SetValue("ElementID", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PopupContent fields.
		/// </summary>
		[RegisterProperty]
		public PopupContentFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PopupContent fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PopupContentFields : AbstractHierarchicalObject<PopupContentFields>
		{
			/// <summary>
			/// The content item of type PopupContent that is a target of the extended API.
			/// </summary>
			private readonly PopupContent mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PopupContentFields" /> class with the specified content item of type PopupContent.
			/// </summary>
			/// <param name="instance">The content item of type PopupContent that is a target of the extended API.</param>
			public PopupContentFields(PopupContent instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// AccordionContentID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PopupContentID;
				}
				set
				{
					mInstance.PopupContentID = value;
				}
			}


			/// <summary>
			/// Content header.
			/// </summary>
			public string ContentHeader
			{
				get
				{
					return mInstance.ContentHeader;
				}
				set
				{
					mInstance.ContentHeader = value;
				}
			}


			/// <summary>
			/// Enable.
			/// </summary>
			public bool GAEnable
			{
				get
				{
					return mInstance.GAEnable;
				}
				set
				{
					mInstance.GAEnable = value;
				}
			}


			/// <summary>
			/// Event code.
			/// </summary>
			public string GAEventCode
			{
				get
				{
					return mInstance.GAEventCode;
				}
				set
				{
					mInstance.GAEventCode = value;
				}
			}


			/// <summary>
			/// Category.
			/// </summary>
			public string GACategory
			{
				get
				{
					return mInstance.GACategory;
				}
				set
				{
					mInstance.GACategory = value;
				}
			}


			/// <summary>
			/// Action.
			/// </summary>
			public string GAAction
			{
				get
				{
					return mInstance.GAAction;
				}
				set
				{
					mInstance.GAAction = value;
				}
			}


			/// <summary>
			/// Label.
			/// </summary>
			public string GALabel
			{
				get
				{
					return mInstance.GALabel;
				}
				set
				{
					mInstance.GALabel = value;
				}
			}


			/// <summary>
			/// Element ID.
			/// </summary>
			public string ElementID
			{
				get
				{
					return mInstance.ElementID;
				}
				set
				{
					mInstance.ElementID = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PopupContent" /> class.
		/// </summary>
		public PopupContent() : base(CLASS_NAME)
		{
			mFields = new PopupContentFields(this);
		}

		#endregion
	}
}