//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.BAY;

[assembly: RegisterDocumentType(TabFolder.CLASS_NAME, typeof(TabFolder))]

namespace CMS.DocumentEngine.Types.BAY
{
	/// <summary>
	/// Represents a content item of type TabFolder.
	/// </summary>
	public partial class TabFolder : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BAY.TabFolder";


		/// <summary>
		/// The instance of the class that provides extended API for working with TabFolder fields.
		/// </summary>
		private readonly TabFolderFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// NavigationFolderID.
		/// </summary>
		[DatabaseIDField]
		public int TabFolderID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("TabFolderID"), 0);
			}
			set
			{
				SetValue("TabFolderID", value);
			}
		}


		/// <summary>
		/// Element ID.
		/// </summary>
		[DatabaseField]
		public string ElementID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementID"), @"");
			}
			set
			{
				SetValue("ElementID", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Folder name.
		/// </summary>
		[DatabaseField]
		public string FolderName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FolderName"), @"");
			}
			set
			{
				SetValue("FolderName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with TabFolder fields.
		/// </summary>
		[RegisterProperty]
		public TabFolderFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with TabFolder fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TabFolderFields : AbstractHierarchicalObject<TabFolderFields>
		{
			/// <summary>
			/// The content item of type TabFolder that is a target of the extended API.
			/// </summary>
			private readonly TabFolder mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TabFolderFields" /> class with the specified content item of type TabFolder.
			/// </summary>
			/// <param name="instance">The content item of type TabFolder that is a target of the extended API.</param>
			public TabFolderFields(TabFolder instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// NavigationFolderID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.TabFolderID;
				}
				set
				{
					mInstance.TabFolderID = value;
				}
			}


			/// <summary>
			/// Element ID.
			/// </summary>
			public string ElementID
			{
				get
				{
					return mInstance.ElementID;
				}
				set
				{
					mInstance.ElementID = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}


			/// <summary>
			/// Folder name.
			/// </summary>
			public string FolderName
			{
				get
				{
					return mInstance.FolderName;
				}
				set
				{
					mInstance.FolderName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="TabFolder" /> class.
		/// </summary>
		public TabFolder() : base(CLASS_NAME)
		{
			mFields = new TabFolderFields(this);
		}

		#endregion
	}
}