//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.LMP;

[assembly: RegisterDocumentType(ContactBackButton.CLASS_NAME, typeof(ContactBackButton))]

namespace CMS.DocumentEngine.Types.LMP
{
	/// <summary>
	/// Represents a content item of type ContactBackButton.
	/// </summary>
	public partial class ContactBackButton : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "LMP.ContactBackButton";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContactBackButton fields.
		/// </summary>
		private readonly ContactBackButtonFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// NavigationFolderID.
		/// </summary>
		[DatabaseIDField]
		public int ContactBackButtonID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ContactBackButtonID"), 0);
			}
			set
			{
				SetValue("ContactBackButtonID", value);
			}
		}


		/// <summary>
		/// Button cID.
		/// </summary>
		[DatabaseField]
		public string ContactButtonID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactButtonID"), @"ContactBackID");
			}
			set
			{
				SetValue("ContactButtonID", value);
			}
		}


		/// <summary>
		/// Button name.
		/// </summary>
		[DatabaseField]
		public string ContactButtonName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactButtonName"), @"ContactBack");
			}
			set
			{
				SetValue("ContactButtonName", value);
			}
		}


		/// <summary>
		/// Button class.
		/// </summary>
		[DatabaseField]
		public string ContactButtonClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactButtonClass"), @"ds2-btn-register");
			}
			set
			{
				SetValue("ContactButtonClass", value);
			}
		}


		/// <summary>
		/// Element ID.
		/// </summary>
		[DatabaseField]
		public string ElementID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementID"), @"");
			}
			set
			{
				SetValue("ElementID", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ContactBackButton fields.
		/// </summary>
		[RegisterProperty]
		public ContactBackButtonFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ContactBackButton fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContactBackButtonFields : AbstractHierarchicalObject<ContactBackButtonFields>
		{
			/// <summary>
			/// The content item of type ContactBackButton that is a target of the extended API.
			/// </summary>
			private readonly ContactBackButton mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContactBackButtonFields" /> class with the specified content item of type ContactBackButton.
			/// </summary>
			/// <param name="instance">The content item of type ContactBackButton that is a target of the extended API.</param>
			public ContactBackButtonFields(ContactBackButton instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// NavigationFolderID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ContactBackButtonID;
				}
				set
				{
					mInstance.ContactBackButtonID = value;
				}
			}


			/// <summary>
			/// Button cID.
			/// </summary>
			public string ContactButtonID
			{
				get
				{
					return mInstance.ContactButtonID;
				}
				set
				{
					mInstance.ContactButtonID = value;
				}
			}


			/// <summary>
			/// Button name.
			/// </summary>
			public string ContactButtonName
			{
				get
				{
					return mInstance.ContactButtonName;
				}
				set
				{
					mInstance.ContactButtonName = value;
				}
			}


			/// <summary>
			/// Button class.
			/// </summary>
			public string ContactButtonClass
			{
				get
				{
					return mInstance.ContactButtonClass;
				}
				set
				{
					mInstance.ContactButtonClass = value;
				}
			}


			/// <summary>
			/// Element ID.
			/// </summary>
			public string ElementID
			{
				get
				{
					return mInstance.ElementID;
				}
				set
				{
					mInstance.ElementID = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContactBackButton" /> class.
		/// </summary>
		public ContactBackButton() : base(CLASS_NAME)
		{
			mFields = new ContactBackButtonFields(this);
		}

		#endregion
	}
}