//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.LMP;

[assembly: RegisterDocumentType(InsuranceTypeItem.CLASS_NAME, typeof(InsuranceTypeItem))]

namespace CMS.DocumentEngine.Types.LMP
{
	/// <summary>
	/// Represents a content item of type InsuranceTypeItem.
	/// </summary>
	public partial class InsuranceTypeItem : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "LMP.InsuranceTypeItem";


		/// <summary>
		/// The instance of the class that provides extended API for working with InsuranceTypeItem fields.
		/// </summary>
		private readonly InsuranceTypeItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FaqID.
		/// </summary>
		[DatabaseIDField]
		public int InsuranceTypeItemID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("InsuranceTypeItemID"), 0);
			}
			set
			{
				SetValue("InsuranceTypeItemID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Insurance image card.
		/// </summary>
		[DatabaseField]
		public string ImageCard
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ImageCard"), @"");
			}
			set
			{
				SetValue("ImageCard", value);
			}
		}


		/// <summary>
		/// Insurance image card alt.
		/// </summary>
		[DatabaseField]
		public string ImageCardAlt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ImageCardAlt"), @"");
			}
			set
			{
				SetValue("ImageCardAlt", value);
			}
		}


		/// <summary>
		/// รับประกันโดย:.
		/// </summary>
		[DatabaseField]
		public string InsuranceCompanyBy
		{
			get
			{
				return ValidationHelper.GetString(GetValue("InsuranceCompanyBy"), @"");
			}
			set
			{
				SetValue("InsuranceCompanyBy", value);
			}
		}


		/// <summary>
		/// Insurance company alt.
		/// </summary>
		[DatabaseField]
		public string InsuranceCompanyByAlt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("InsuranceCompanyByAlt"), @"");
			}
			set
			{
				SetValue("InsuranceCompanyByAlt", value);
			}
		}


		/// <summary>
		/// รายละเอียดเบี้ยประกัน.
		/// </summary>
		[DatabaseField]
		public string InsurancePremium
		{
			get
			{
				return ValidationHelper.GetString(GetValue("InsurancePremium"), @"");
			}
			set
			{
				SetValue("InsurancePremium", value);
			}
		}


		/// <summary>
		/// รายละเอียดทุนประกันภัย.
		/// </summary>
		[DatabaseField]
		public string InsuranceCapital
		{
			get
			{
				return ValidationHelper.GetString(GetValue("InsuranceCapital"), @"");
			}
			set
			{
				SetValue("InsuranceCapital", value);
			}
		}


		/// <summary>
		/// รายละเอียดการซ่อมและเคลม.
		/// </summary>
		[DatabaseField]
		public string ClaimDetails
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ClaimDetails"), @"");
			}
			set
			{
				SetValue("ClaimDetails", value);
			}
		}


		/// <summary>
		/// รายละเอียดทรัพย์สินบุคคลภายนอก.
		/// </summary>
		[DatabaseField]
		public string ThirdPartyAssets
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ThirdPartyAssets"), @"");
			}
			set
			{
				SetValue("ThirdPartyAssets", value);
			}
		}


		/// <summary>
		/// HasButton.
		/// </summary>
		[DatabaseField]
		public bool HasButton
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("HasButton"), true);
			}
			set
			{
				SetValue("HasButton", value);
			}
		}


		/// <summary>
		/// Button text.
		/// </summary>
		[DatabaseField]
		public string ButtonText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ButtonText"), @"");
			}
			set
			{
				SetValue("ButtonText", value);
			}
		}


		/// <summary>
		/// Link type.
		/// </summary>
		[DatabaseField]
		public int LinkType
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("LinkType"), 3);
			}
			set
			{
				SetValue("LinkType", value);
			}
		}


		/// <summary>
		/// Link page.
		/// </summary>
		[DatabaseField]
		public Guid LinkPageNodeGuid
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("LinkPageNodeGuid"), Guid.Empty);
			}
			set
			{
				SetValue("LinkPageNodeGuid", value);
			}
		}


		/// <summary>
		/// Link URL.
		/// </summary>
		[DatabaseField]
		public string LinkUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkUrl"), @"");
			}
			set
			{
				SetValue("LinkUrl", value);
			}
		}


		/// <summary>
		/// Link target.
		/// </summary>
		[DatabaseField]
		public string LinkTarget
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkTarget"), @"");
			}
			set
			{
				SetValue("LinkTarget", value);
			}
		}


		/// <summary>
		/// On click (Javascript).
		/// </summary>
		[DatabaseField]
		public string LinkOnClick
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkOnClick"), @"");
			}
			set
			{
				SetValue("LinkOnClick", value);
			}
		}


		/// <summary>
		/// Element ID.
		/// </summary>
		[DatabaseField]
		public string ElementID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementID"), @"");
			}
			set
			{
				SetValue("ElementID", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with InsuranceTypeItem fields.
		/// </summary>
		[RegisterProperty]
		public InsuranceTypeItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with InsuranceTypeItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class InsuranceTypeItemFields : AbstractHierarchicalObject<InsuranceTypeItemFields>
		{
			/// <summary>
			/// The content item of type InsuranceTypeItem that is a target of the extended API.
			/// </summary>
			private readonly InsuranceTypeItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="InsuranceTypeItemFields" /> class with the specified content item of type InsuranceTypeItem.
			/// </summary>
			/// <param name="instance">The content item of type InsuranceTypeItem that is a target of the extended API.</param>
			public InsuranceTypeItemFields(InsuranceTypeItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FaqID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.InsuranceTypeItemID;
				}
				set
				{
					mInstance.InsuranceTypeItemID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Insurance image card.
			/// </summary>
			public string ImageCard
			{
				get
				{
					return mInstance.ImageCard;
				}
				set
				{
					mInstance.ImageCard = value;
				}
			}


			/// <summary>
			/// Insurance image card alt.
			/// </summary>
			public string ImageCardAlt
			{
				get
				{
					return mInstance.ImageCardAlt;
				}
				set
				{
					mInstance.ImageCardAlt = value;
				}
			}


			/// <summary>
			/// รับประกันโดย:.
			/// </summary>
			public string InsuranceCompanyBy
			{
				get
				{
					return mInstance.InsuranceCompanyBy;
				}
				set
				{
					mInstance.InsuranceCompanyBy = value;
				}
			}


			/// <summary>
			/// Insurance company alt.
			/// </summary>
			public string InsuranceCompanyByAlt
			{
				get
				{
					return mInstance.InsuranceCompanyByAlt;
				}
				set
				{
					mInstance.InsuranceCompanyByAlt = value;
				}
			}


			/// <summary>
			/// รายละเอียดเบี้ยประกัน.
			/// </summary>
			public string InsurancePremium
			{
				get
				{
					return mInstance.InsurancePremium;
				}
				set
				{
					mInstance.InsurancePremium = value;
				}
			}


			/// <summary>
			/// รายละเอียดทุนประกันภัย.
			/// </summary>
			public string InsuranceCapital
			{
				get
				{
					return mInstance.InsuranceCapital;
				}
				set
				{
					mInstance.InsuranceCapital = value;
				}
			}


			/// <summary>
			/// รายละเอียดการซ่อมและเคลม.
			/// </summary>
			public string ClaimDetails
			{
				get
				{
					return mInstance.ClaimDetails;
				}
				set
				{
					mInstance.ClaimDetails = value;
				}
			}


			/// <summary>
			/// รายละเอียดทรัพย์สินบุคคลภายนอก.
			/// </summary>
			public string ThirdPartyAssets
			{
				get
				{
					return mInstance.ThirdPartyAssets;
				}
				set
				{
					mInstance.ThirdPartyAssets = value;
				}
			}


			/// <summary>
			/// HasButton.
			/// </summary>
			public bool HasButton
			{
				get
				{
					return mInstance.HasButton;
				}
				set
				{
					mInstance.HasButton = value;
				}
			}


			/// <summary>
			/// Button text.
			/// </summary>
			public string ButtonText
			{
				get
				{
					return mInstance.ButtonText;
				}
				set
				{
					mInstance.ButtonText = value;
				}
			}


			/// <summary>
			/// Link type.
			/// </summary>
			public int LinkType
			{
				get
				{
					return mInstance.LinkType;
				}
				set
				{
					mInstance.LinkType = value;
				}
			}


			/// <summary>
			/// Link page.
			/// </summary>
			public Guid LinkPageNodeGuid
			{
				get
				{
					return mInstance.LinkPageNodeGuid;
				}
				set
				{
					mInstance.LinkPageNodeGuid = value;
				}
			}


			/// <summary>
			/// Link URL.
			/// </summary>
			public string LinkUrl
			{
				get
				{
					return mInstance.LinkUrl;
				}
				set
				{
					mInstance.LinkUrl = value;
				}
			}


			/// <summary>
			/// Link target.
			/// </summary>
			public string LinkTarget
			{
				get
				{
					return mInstance.LinkTarget;
				}
				set
				{
					mInstance.LinkTarget = value;
				}
			}


			/// <summary>
			/// On click (Javascript).
			/// </summary>
			public string LinkOnClick
			{
				get
				{
					return mInstance.LinkOnClick;
				}
				set
				{
					mInstance.LinkOnClick = value;
				}
			}


			/// <summary>
			/// Element ID.
			/// </summary>
			public string ElementID
			{
				get
				{
					return mInstance.ElementID;
				}
				set
				{
					mInstance.ElementID = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="InsuranceTypeItem" /> class.
		/// </summary>
		public InsuranceTypeItem() : base(CLASS_NAME)
		{
			mFields = new InsuranceTypeItemFields(this);
		}

		#endregion
	}
}