//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.LMP;

[assembly: RegisterDocumentType(InsuranceWhyItem.CLASS_NAME, typeof(InsuranceWhyItem))]

namespace CMS.DocumentEngine.Types.LMP
{
	/// <summary>
	/// Represents a content item of type InsuranceWhyItem.
	/// </summary>
	public partial class InsuranceWhyItem : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "LMP.InsuranceWhyItem";


		/// <summary>
		/// The instance of the class that provides extended API for working with InsuranceWhyItem fields.
		/// </summary>
		private readonly InsuranceWhyItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FaqID.
		/// </summary>
		[DatabaseIDField]
		public int InsuranceWhyItemID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("InsuranceWhyItemID"), 0);
			}
			set
			{
				SetValue("InsuranceWhyItemID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string Description
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Description"), @"");
			}
			set
			{
				SetValue("Description", value);
			}
		}


		/// <summary>
		/// Logo image.
		/// </summary>
		[DatabaseField]
		public string LogoImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LogoImage"), @"");
			}
			set
			{
				SetValue("LogoImage", value);
			}
		}


		/// <summary>
		/// Logo image alt.
		/// </summary>
		[DatabaseField]
		public string LogoImageAlt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LogoImageAlt"), @"");
			}
			set
			{
				SetValue("LogoImageAlt", value);
			}
		}


		/// <summary>
		/// Link type.
		/// </summary>
		[DatabaseField]
		public int LinkType
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("LinkType"), 2);
			}
			set
			{
				SetValue("LinkType", value);
			}
		}


		/// <summary>
		/// Link text.
		/// </summary>
		[DatabaseField]
		public string LinkText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkText"), @"");
			}
			set
			{
				SetValue("LinkText", value);
			}
		}


		/// <summary>
		/// Link page.
		/// </summary>
		[DatabaseField]
		public Guid LinkPageNodeGuid
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("LinkPageNodeGuid"), Guid.Empty);
			}
			set
			{
				SetValue("LinkPageNodeGuid", value);
			}
		}


		/// <summary>
		/// Link URL.
		/// </summary>
		[DatabaseField]
		public string LinkUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkUrl"), @"");
			}
			set
			{
				SetValue("LinkUrl", value);
			}
		}


		/// <summary>
		/// Link target.
		/// </summary>
		[DatabaseField]
		public string LinkTarget
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkTarget"), @"");
			}
			set
			{
				SetValue("LinkTarget", value);
			}
		}


		/// <summary>
		/// On click (Javascript).
		/// </summary>
		[DatabaseField]
		public string LinkOnClick
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkOnClick"), @"");
			}
			set
			{
				SetValue("LinkOnClick", value);
			}
		}


		/// <summary>
		/// Element ID.
		/// </summary>
		[DatabaseField]
		public string ElementID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementID"), @"");
			}
			set
			{
				SetValue("ElementID", value);
			}
		}


		/// <summary>
		/// Invisible.
		/// </summary>
		[DatabaseField]
		public bool Invisible
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Invisible"), false);
			}
			set
			{
				SetValue("Invisible", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with InsuranceWhyItem fields.
		/// </summary>
		[RegisterProperty]
		public InsuranceWhyItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with InsuranceWhyItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class InsuranceWhyItemFields : AbstractHierarchicalObject<InsuranceWhyItemFields>
		{
			/// <summary>
			/// The content item of type InsuranceWhyItem that is a target of the extended API.
			/// </summary>
			private readonly InsuranceWhyItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="InsuranceWhyItemFields" /> class with the specified content item of type InsuranceWhyItem.
			/// </summary>
			/// <param name="instance">The content item of type InsuranceWhyItem that is a target of the extended API.</param>
			public InsuranceWhyItemFields(InsuranceWhyItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FaqID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.InsuranceWhyItemID;
				}
				set
				{
					mInstance.InsuranceWhyItemID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string Description
			{
				get
				{
					return mInstance.Description;
				}
				set
				{
					mInstance.Description = value;
				}
			}


			/// <summary>
			/// Logo image.
			/// </summary>
			public string LogoImage
			{
				get
				{
					return mInstance.LogoImage;
				}
				set
				{
					mInstance.LogoImage = value;
				}
			}


			/// <summary>
			/// Logo image alt.
			/// </summary>
			public string LogoImageAlt
			{
				get
				{
					return mInstance.LogoImageAlt;
				}
				set
				{
					mInstance.LogoImageAlt = value;
				}
			}


			/// <summary>
			/// Link type.
			/// </summary>
			public int LinkType
			{
				get
				{
					return mInstance.LinkType;
				}
				set
				{
					mInstance.LinkType = value;
				}
			}


			/// <summary>
			/// Link text.
			/// </summary>
			public string LinkText
			{
				get
				{
					return mInstance.LinkText;
				}
				set
				{
					mInstance.LinkText = value;
				}
			}


			/// <summary>
			/// Link page.
			/// </summary>
			public Guid LinkPageNodeGuid
			{
				get
				{
					return mInstance.LinkPageNodeGuid;
				}
				set
				{
					mInstance.LinkPageNodeGuid = value;
				}
			}


			/// <summary>
			/// Link URL.
			/// </summary>
			public string LinkUrl
			{
				get
				{
					return mInstance.LinkUrl;
				}
				set
				{
					mInstance.LinkUrl = value;
				}
			}


			/// <summary>
			/// Link target.
			/// </summary>
			public string LinkTarget
			{
				get
				{
					return mInstance.LinkTarget;
				}
				set
				{
					mInstance.LinkTarget = value;
				}
			}


			/// <summary>
			/// On click (Javascript).
			/// </summary>
			public string LinkOnClick
			{
				get
				{
					return mInstance.LinkOnClick;
				}
				set
				{
					mInstance.LinkOnClick = value;
				}
			}


			/// <summary>
			/// Element ID.
			/// </summary>
			public string ElementID
			{
				get
				{
					return mInstance.ElementID;
				}
				set
				{
					mInstance.ElementID = value;
				}
			}


			/// <summary>
			/// Invisible.
			/// </summary>
			public bool Invisible
			{
				get
				{
					return mInstance.Invisible;
				}
				set
				{
					mInstance.Invisible = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="InsuranceWhyItem" /> class.
		/// </summary>
		public InsuranceWhyItem() : base(CLASS_NAME)
		{
			mFields = new InsuranceWhyItemFields(this);
		}

		#endregion
	}
}